### ISSUE TITLE
Encoder does not verify that writes succeeded when flushing

### ISSUE THREAD

**Issue by nemequ** [fusiyuan2010/CSC#10]
One of my unit tests, which CSC fails, is basically to verify that when a write fails the encoder returns an error instead of silently succeeding.

The issue starts at [csc_coder.cpp:61](https://github.com/fusiyuan2010/CSC/blob/master/src/libcsc/csc_coder.cpp#L61) where the return value of `WriteBCData` is discarded without verifying that it is `== bc_size_`.  I'm guessing a similar issue exists in the preceding line.

`CSCEnc_Encoder_Flush` has a non-void return value, but `CSCEncoder::Flush` and `Coder::Flush` both return void.

**Comment by fusiyuan2010** [comment]
thanks! 6119a788fce5f1dcdc5cd41d1e111f7c4e59e1c1  fixed here
