### ISSUE TITLE
Having to check the file size limits usefulness of streaming API

### ISSUE THREAD

**Issue by nemequ** [fusiyuan2010/CSC#2]
`csc.cpp` checks the file and limits the dict size to the file size.  Having to check this severely limits the streaming API since the size of the stream has to be known ahead of time, meaning it can't be used with pipes, over the network, etc.

**Comment by fusiyuan2010** [comment]
No it does not mean the dict size has to be limited to file size, this line of code is just for avoiding the waste of memory use. Because it makes no sense to have the dictionary size greater than the file size.

**Comment by nemequ** [comment]
Ah, okay, I thought it was a requirement.  Thanks.
