### ISSUE TITLE
ODR violations

### ISSUE THREAD

**Issue by nemequ** [fusiyuan2010/CSC#9]
There are some violations of the [one-definition rule](https://en.wikipedia.org/wiki/One_Definition_Rule).  csc_enc.cpp and csc_dec.cpp both define a CSCInstance type, but the fields are different.

See https://travis-ci.org/quixdb/squash/jobs/100065566 for an example of the error (it only happens when building a release, my guess is that the compiler only catches it when link-time optimization is enabled).

**Comment by fusiyuan2010** [comment]
5b85758ad01067cde828f3e28a7c3ee56fc2deb1  fixed
